/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicle.fleet.java.gui;

import java.awt.Color;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import vehicle.fleet.java.VehicleFleet;
import vehicle.fleet.java.vehicles.*;

/**
 * Jármű látrehozás GUI.
 * @author zsolti-pc
 */
public class VehicleFleetAddGUI extends javax.swing.JFrame {

    /**
     * Creates new form VehicleFleetAddGUI
     */
    public VehicleFleetAddGUI() {
        
        initComponents();
        
        PassengerInput.setVisible(false);
        PassengerLabel.setVisible(false);
        FieldsPanel.setVisible(false);
        Separator.setVisible(false);
        JFormattedTextField tf = ((JSpinner.DefaultEditor) PassengerInput.getEditor()).getTextField();
        tf.setEditable(false);
        tf.setBackground(Color.white);
        tf.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Placeholder = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FieldsPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        MaxSpeedInput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        KMTraveledInput = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ConsumptionInput = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CarryInput = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ErrorLabel = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        TypeComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        PriceInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ColorComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        PassengerInput = new javax.swing.JSpinner();
        WeightInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PassengerLabel = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout PlaceholderLayout = new javax.swing.GroupLayout(Placeholder);
        Placeholder.setLayout(PlaceholderLayout);
        PlaceholderLayout.setHorizontalGroup(
            PlaceholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PlaceholderLayout.setVerticalGroup(
            PlaceholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Vehicle");

        jLabel7.setText("Max speed");

        MaxSpeedInput.setText("0");
        MaxSpeedInput.setToolTipText("Max speeds");
        MaxSpeedInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaxSpeedInputActionPerformed(evt);
            }
        });

        jLabel8.setText("KM traveled");

        KMTraveledInput.setText("0");
        KMTraveledInput.setToolTipText("KM traveled");

        jLabel9.setText("Consumption");

        ConsumptionInput.setText("0.0");
        ConsumptionInput.setToolTipText("Consumption l/km");
        ConsumptionInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsumptionInputActionPerformed(evt);
            }
        });

        jLabel10.setText("Max carry weight");

        CarryInput.setText("0");
        CarryInput.setToolTipText("Max carry weight");
        CarryInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarryInputActionPerformed(evt);
            }
        });

        jLabel12.setText("km");

        jLabel13.setText("km/h");

        jLabel14.setText("l/100km");

        jLabel15.setText("km");

        javax.swing.GroupLayout FieldsPanelLayout = new javax.swing.GroupLayout(FieldsPanel);
        FieldsPanel.setLayout(FieldsPanelLayout);
        FieldsPanelLayout.setHorizontalGroup(
            FieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FieldsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGroup(FieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FieldsPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(ConsumptionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addGroup(FieldsPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(FieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaxSpeedInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KMTraveledInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(FieldsPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(CarryInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)))
                .addContainerGap())
        );
        FieldsPanelLayout.setVerticalGroup(
            FieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FieldsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(MaxSpeedInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(FieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(KMTraveledInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(16, 16, 16)
                .addGroup(FieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ConsumptionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CarryInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        SaveButton.setText("Save!");
        SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveButtonMouseClicked(evt);
            }
        });
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        SaveButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SaveButtonKeyPressed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        BackButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BackButtonKeyPressed(evt);
            }
        });

        jLabel11.setText("Vehicle type");

        TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bicycle", "Car", "MiniBus", "Bus", "Helicopter" }));
        TypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TypeComboBoxItemStateChanged(evt);
            }
        });

        jLabel2.setText("Price");

        PriceInput.setText("0");
        PriceInput.setToolTipText("Price of the vehicle");
        PriceInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceInputActionPerformed(evt);
            }
        });

        jLabel3.setText("coin");

        jLabel4.setText("Color");

        ColorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Black", "2 Red", "3 White", "4 Green", "5 Brown", "6 Blue", "7 Orange", "8 Yellow", "9 Purple", "10 Gray", "11 Pink", "12 Tan" }));

        jLabel5.setText("Weight");

        PassengerInput.setFocusable(false);
        PassengerInput.setValue(1);
        PassengerInput.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PassengerInputStateChanged(evt);
            }
        });

        WeightInput.setText("0");
        WeightInput.setToolTipText("Weight of the vehicle in kg");
        WeightInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightInputActionPerformed(evt);
            }
        });

        jLabel6.setText("kg");

        PassengerLabel.setText("Max Passenger");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(PassengerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(ColorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PassengerInput))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(WeightInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ColorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(WeightInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassengerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassengerLabel))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Separator)
                            .addComponent(FieldsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4))
                    .addComponent(ErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(4, 4, 4)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FieldsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(BackButton))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(592, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaxSpeedInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxSpeedInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaxSpeedInputActionPerformed

    private void ConsumptionInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsumptionInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsumptionInputActionPerformed

    private void SaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseClicked
        int type = TypeComboBox.getSelectedIndex();
        int color = ColorComboBox.getSelectedIndex()+1;
        int passenger = (int) PassengerInput.getValue();
        try{
            int price = (int) validateField(PriceInput);
            int weight = (int) validateField(WeightInput);
            int mspeed = (int) validateField(MaxSpeedInput);
            int km = (int) validateField(KMTraveledInput);
            float cons = validateField(ConsumptionInput);
            float carry = validateField(CarryInput);
            switch(type){
                case 0:
                    Bike b = new Bike(price, color, weight);
                    VehicleFleet.getInstance().add(b);
                    setMessage("Bike created!", true);
                    break;
                case 1:
                    Car c = new Car(price, color, weight, passenger, mspeed, km, cons, carry);
                    VehicleFleet.getInstance().add(c);
                    setMessage("Car created!", true);
                    break;
                case 2:
                    MiniBus mb = new MiniBus(price, color, weight, passenger, mspeed, km, cons, carry);
                    VehicleFleet.getInstance().add(mb);
                    setMessage("MiniBus created!", true);
                    break;
                case 3:
                    Bus bus = new Bus(price, color, weight, passenger, mspeed, km, cons, carry);
                    VehicleFleet.getInstance().add(bus);
                    setMessage("Bus created!", true);
                    break;
                case 4:
                    Helicopter h = new Helicopter(price, color, weight, passenger, mspeed, km, cons, carry);
                    VehicleFleet.getInstance().add(h);
                    setMessage("Helicopter created!", true);
                    break;
                default:
                   setMessage("Nothing created!", false);
                   break;
            }
        }catch(Exception e){
            setMessage(e.getMessage(), false);
        }        
    }//GEN-LAST:event_SaveButtonMouseClicked

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void SaveButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SaveButtonKeyPressed
        
    }//GEN-LAST:event_SaveButtonKeyPressed

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        dispose();
        new VehicleFleetMainGUI().setVisible(true);
    }//GEN-LAST:event_BackButtonMouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void BackButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BackButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonKeyPressed

    private void PriceInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceInputActionPerformed

    private void WeightInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeightInputActionPerformed

    private void TypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TypeComboBoxItemStateChanged
        if(TypeComboBox.getSelectedIndex() == 0){
            PassengerInput.setVisible(false);
            PassengerLabel.setVisible(false);
            FieldsPanel.setVisible(false);
            Separator.setVisible(false);
        }else{
            PassengerInput.setVisible(true);
            PassengerLabel.setVisible(true);
            FieldsPanel.setVisible(true);
            Separator.setVisible(true);
        }
    }//GEN-LAST:event_TypeComboBoxItemStateChanged

    private void CarryInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarryInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarryInputActionPerformed

    private void PassengerInputStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PassengerInputStateChanged
        if((int) PassengerInput.getPreviousValue() < 0) PassengerInput.setValue(0);
    }//GEN-LAST:event_PassengerInputStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleFleetAddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleFleetAddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleFleetAddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleFleetAddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleFleetAddGUI().setVisible(true);
            }
        });
    }
    
    public float validateField(javax.swing.JTextField field) throws Exception{
        if(field.getText().isEmpty()) throw new Exception("Field must not be empty!");
        try{
            return Float.parseFloat(field.getText());
        }catch(IllegalArgumentException e){
            throw e;
        }
    }
    
    public void setMessage(String msg, boolean succ){
        ErrorLabel.setText(msg);
        ErrorLabel.setForeground((succ) ? Color.GREEN : Color.RED);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField CarryInput;
    private javax.swing.JComboBox<String> ColorComboBox;
    private javax.swing.JTextField ConsumptionInput;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JPanel FieldsPanel;
    private javax.swing.JTextField KMTraveledInput;
    private javax.swing.JTextField MaxSpeedInput;
    private javax.swing.JSpinner PassengerInput;
    private javax.swing.JLabel PassengerLabel;
    private javax.swing.JPanel Placeholder;
    private javax.swing.JTextField PriceInput;
    private javax.swing.JButton SaveButton;
    private javax.swing.JSeparator Separator;
    private javax.swing.JComboBox<String> TypeComboBox;
    private javax.swing.JTextField WeightInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
